In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Artificial intelligence is transforming the world.",
    "ChatGPT is a powerful language model developed by OpenAI.",
    "Data science involves statistics, programming, and domain expertise.",
    "The weather today is sunny with a chance of rain in the evening.",
    "He bought a new laptop for his machine learning project.",
    "Natural language processing enables machines to understand human language.",
    "The stock market showed a significant drop yesterday.",
    "Python is a versatile programming language used in many fields.",
    "She traveled to Japan to experience the cherry blossom season."
]


In [3]:
voc_size = 10000  # Size of the vocabulary

In [4]:
## One-Hot Representation

In [5]:
## one hot representation
one_hot_repre = [ one_hot(words, voc_size) for words in sentences ]

In [6]:
one_hot_repre

[[7087, 3752, 7397, 4716, 4573, 3262, 7087, 8214, 393],
 [1107, 7930, 461, 74, 7087, 6127],
 [3846, 461, 7218, 677, 9280, 7282, 7875, 4333, 4397],
 [5546, 1276, 3634, 5012, 9803, 5997, 8026, 4346],
 [7087, 4224, 2402, 461, 5510, 2659, 7218, 8350, 5582, 6217, 8193, 7087, 2919],
 [3516, 4811, 7218, 9264, 4425, 7596, 9275, 6951, 831, 5037],
 [1281, 9280, 2366, 886, 2552, 8737, 7230, 7328, 9280],
 [7087, 6670, 7467, 241, 7218, 2671, 8968, 386],
 [6441, 461, 7218, 7707, 9803, 9280, 4750, 8193, 3624, 4976],
 [7138, 827, 8737, 4076, 8737, 2054, 7087, 2811, 332, 1360]]

In [7]:
# Word embedding representation
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [8]:
import numpy as np

In [9]:
## Padding sequences

In [ ]:
embedded_docs = pad_sequences(one_hot_repre, padding = "pre", maxlen=sen_length)   # pre padding means padding at the beginning of the sequence
embedded_docs

array([[   0,    0,    0,    0, 7087, 3752, 7397, 4716, 4573, 3262, 7087,
        8214,  393],
       [   0,    0,    0,    0,    0,    0,    0, 1107, 7930,  461,   74,
        7087, 6127],
       [   0,    0,    0,    0, 3846,  461, 7218,  677, 9280, 7282, 7875,
        4333, 4397],
       [   0,    0,    0,    0,    0, 5546, 1276, 3634, 5012, 9803, 5997,
        8026, 4346],
       [7087, 4224, 2402,  461, 5510, 2659, 7218, 8350, 5582, 6217, 8193,
        7087, 2919],
       [   0,    0,    0, 3516, 4811, 7218, 9264, 4425, 7596, 9275, 6951,
         831, 5037],
       [   0,    0,    0,    0, 1281, 9280, 2366,  886, 2552, 8737, 7230,
        7328, 9280],
       [   0,    0,    0,    0,    0, 7087, 6670, 7467,  241, 7218, 2671,
        8968,  386],
       [   0,    0,    0, 6441,  461, 7218, 7707, 9803, 9280, 4750, 8193,
        3624, 4976],
       [   0,    0,    0, 7138,  827, 8737, 4076, 8737, 2054, 7087, 2811,
         332, 1360]])

In [11]:
## model creation

In [12]:
## feature representation
dim = 14 # Dimension of the embedding vector

In [13]:
model = Sequential()
# not working until forcefully create the model OR train the model then the model.summary won't be a blank---> # model.add(Embedding(voc_size, dim, input_length=sen_length))  # voc_size is the size of the vocabulary, dim is the dimension of the embedding vector, and sen_length is the length of the input sequences
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.build(input_shape=(None, sen_length)) # Build the model with the specified input shape
model.compile("adam","mse")  # Compile the model with Adam optimizer and mean squared error loss

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 13, 14)         │       140,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140,000 (546.88 KB)

 Trainable params: 140,000 (546.88 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
# Checking the vector representation 
model.predict(embedded_docs)  # Predicting the embedding for the first sentence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step


array([[[ 0.00827418,  0.04490118,  0.00658356, ..., -0.03265851,
          0.04511983, -0.02386363],
        [ 0.00827418,  0.04490118,  0.00658356, ..., -0.03265851,
          0.04511983, -0.02386363],
        [ 0.00827418,  0.04490118,  0.00658356, ..., -0.03265851,
          0.04511983, -0.02386363],
        ...,
        [-0.01166555,  0.02414724,  0.03363593, ..., -0.02017288,
          0.01755381,  0.02066621],
        [-0.03490542, -0.01280242, -0.01351263, ..., -0.0052886 ,
          0.04435058,  0.04611344],
        [ 0.03105808, -0.04536628,  0.03574539, ..., -0.00756298,
         -0.03300504, -0.00876682]],

       [[ 0.00827418,  0.04490118,  0.00658356, ..., -0.03265851,
          0.04511983, -0.02386363],
        [ 0.00827418,  0.04490118,  0.00658356, ..., -0.03265851,
          0.04511983, -0.02386363],
        [ 0.00827418,  0.04490118,  0.00658356, ..., -0.03265851,
          0.04511983, -0.02386363],
        ...,
        [ 0.02213326,  0.00152139,  0.01586223, ...,  

In [16]:
# vector representation of the first sentence
model.predict(embedded_docs[0].reshape(1, -1))[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


array([ 0.00827418,  0.04490118,  0.00658356, -0.02933114,  0.00283289,
        0.04276994,  0.00647979,  0.01986936,  0.03089459,  0.01822174,
        0.00323766, -0.03265851,  0.04511983, -0.02386363], dtype=float32)

In [17]:
embedded_docs[0].reshape(1, -1)

array([[   0,    0,    0,    0, 7087, 3752, 7397, 4716, 4573, 3262, 7087,
        8214,  393]])